behaviors:
  MLAgent:
    trainer_type: sac
    hyperparameters:
      batch_size: 16
      buffer_size: 4086
      learning_rate: 3.0e-4
      buffer_init_steps: 500
      init_entcoef: 1.0
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      rnd:
        gamma: 0.90
        strength: 0.001
        network_settings:
          normalize: false
          hidden_units: 64
          num_layers: 2
        learning_rate: 3e-4
      curiosity:
        gamma: 0.90
        strength: 0.003
        network_settings:
          normalize: false
          hidden_units: 64
          num_layers: 2
    max_steps: 500000
    time_horizon: 64
    summary_freq: 100
