behaviors:
  MLAgent:
    trainer_type: sac
    hyperparameters:
      batch_size: 64
      buffer_size: 64000
      learning_rate: 3.0e-4
      buffer_init_steps: 3000
      init_entcoef: 1.0
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9995
        strength: 1.0
    max_steps: 50000
    time_horizon: 512
    summary_freq: 100
  MLAgent2:
    trainer_type: sac
    hyperparameters:
      batch_size: 64
      buffer_size: 64000
      learning_rate: 3.0e-4
      buffer_init_steps: 3000
      init_entcoef: 0.6
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9995
        strength: 1.0
    max_steps: 50000
    time_horizon: 512
    summary_freq: 100