behaviors:
  MLAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      rnd:
        gamma: 0.90
        strength: 0.005
        network_settings:
          normalize: false
          hidden_units: 64
          num_layers: 2
        learning_rate: 3e-4
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000